version: '3'
services:
  server1:
    build:
      context: ./docker
    ports:
      - "8081:8000"
    environment:
      - SERVER_ID=1

  server2:
    build:
      context: ./docker
    ports:
      - "8082:8000"
    environment:
      - SERVER_ID=2

  server3:
    build:
      context: ./docker
    ports:
      - "8083:8000"
    environment:
      - SERVER_ID=3